<div class="client_content">
<div class="whttrading"><br /><br />
<h1 align="center">Economic Callender</h1>
<p>Economic Challender  is a study of the economic climate in countries whose currency the traders trade and how the economic factors affect the price of those currency.</p>
<p>It provides information on how the big political and economic events influence the currency markets. Speeches that include economic numbers given by important politicians and statesmen can have a considerable affect on the price of a currency and they should be closely watched especially those speeches that concern the United States and therefore the dollar.</p>
<p>It is important that as a trader the economic calendar is checked for upcoming economic news. The calendar is the creation of economists who predict upcoming economic figures before they are announced and once announced the numbers are compared to the consensus forecast. As you can see from the calendar extract below each announcement has an importance factor attached to it.
The more important the data is the more volatile the market will be immediately after the news release. The highest volatility is in the first 3 or 4 minutes but can continue for 10 minutes before settling down to reflect the new market swing reflecting the data. Volatility is dependent on how positive or negative are the actual data when compared to the forecast data and how important the economic data is.</p><br />
<p>The key fundamental economic data that traders should watch out for and know when they are going to be released are:</p>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Interest rates – </h3><p>Investors tend to move assets to the higher rates.</p><br />
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Employment – </h3><p>Reduction in employment often leads to a weak economy.</p><br />
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trade Balance – </h3><p>A trade deficit usually means that the local currency is weak.</p><br />
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gross Domestic Product – </h3><p>The primary indicator concerning the health of the economy.</p><br />
<p>When using an forex economic calendar a trader should be aware of the importance of the data, the timing of the news release, what impact will differences between the forecast numbers and the actual numbers have on the market and when any reversionary data is due as that to can have an impact on price?</p>
<p>Other areas which are important for a fundamental trader to watch carefully are speeches and announcements made by key political and banking people. Any speech by the chairman of a central bank is worth listening to, especially the chairman of the Federal Reserve Bank. Also speeches by key economic ministers such as the Secretary of the Treasury in the United States and the Chancellor of the Exchequer in the UK should be watched for any economic announcement that might cause currency price movements.</p><br />
<h2 align="left">Whose speeches to keep an eye on?</h2>
<p>Chairman of the Federal Reserve Bank of USA, Secretary of the Treasury, President of the Federal Reserve Bank of San Francisco and so on. Speeches of those prominent people are watched closely by traders.</p><br />
<h3 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;What are the most powerful figures that move Forex market?</h3>
<h3 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Interest rate</h3>
<p>Traditionally, if a country raises its interest rates, its currency will strengthen because investors will shift their assets to that country to gain higher returns.</p> <br />
<h3 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Employment situation</h3>
<p>Decreases in the payroll employment are considered as signs of a weak economic activity that could eventually lead to lower interest rates, which has negative impact on the currency.</p><br />
<h3 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trade balance, budget and treasury budget</h3> 
<p>A country that has a significant Trade Balance deficit will generally have a weak currency as there will be continuouscommercial sellings of its currency.</p><br />
<h3 align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gross Domestic Product(GDP)</h3>
<p>GDP is reported quarterly and is followed very closely as it is a primary indicator of the strength of economic activity. 
A high GDP figure is usually followed by expectations of higher interest rates, which is mostly positive for the currency.</p><br />


</div>
</div>