<div class="client_content">
<div class="whttrading"><br /><br />
<h1 align="center">Forex Indicators</h1>
<p>Indicators are used for identifying, or even creating patterns from the chaos of the currency market. In all cases, they receive the raw market data as the basic input, and manipulate it in differing ways to create (as opposed to discover) actionable trading scenarios. The natural consequence of this description is that indicators are not tools of prediction.  Instead, they are used to give order to the price data, so that it is possible to identify possible opportunities which can be exploited profitably by the trader. No indicator is right or wrong with respect to the signals that it emits, but each of them must be used with an appropriate money management strategy in order to deliver the desired results.
There are many different kinds of indicators, and it is not at all a hard task to define one's own tools for the purpose of evaluating the market provided that a basic literacy in averages is attained, what is desired from the created indicator is made clear. Different constructions will lead to differing techniques which can then be employed most effectively as part of a trading strategy.</p>
<p>So you can regard indicators as your compass and ruler in navigating waves of the forex market. We would use a compass or a ruler to predict when or where a storm will hit, but every sailor knows their usefulness in defining a path over the high seas. Use your indicators to plan your journeys in forex, while protecting your funds with proper money management techniques, and all will be well for you.</p><br />

<h1 align="center">Some Famous Indicators in Forex Trading</h1><br /><br />
<h1 align="center"> Moving Averages: What Are They?</h1>
<p>Moving Averages are technical tools designed to measure the momentum and direction of a trend. The idea behind their creation is simple. Price action is thought to fluctuate around the average value over a period of time, and we can expect to be able to the represent the market's momentum by calculating if the current prices are above or below the market's average value. But since the total length of the time period that must be included in the calculation of the average is too large (are we going to begin in 1980, or the year 2000 while computing our time series?), we pick the period arbitrarily, and update the average as time progresses.</p><br />

<h2 align="left">Why Should I Use Moving Averages?</h2>
<p>Moving averages are some of the most useful and effective gauges of market action in a trending market. Crossovers, divergences, as well as trends of the moving average itself can be used to analyze and crystallize the signals that can be distilled from the market action, which can then be used to help us make future decisions about our trades.</p><br />

<h2 align="left">Types of Moving Averages</h2>
<p>There are a large number of moving averages available for traders. Some of them are:</p><br />
<h2 align="left">Simple Moving Average</h2>
<p>The simple moving average is the most basic of these tools. It simply sums up the cloaisng prices over a specified time, and divides them by the duration of the period, reaching at the value of the indicator. No weighting is used, and no smoothing factor is applied.</p><br />

<h2 align="left">Exponential Moving Average</h2>
<p>The exponential moving average is one of a number of different moving average types that gives greater value to the most recent prices. As its name implies, the weighting is done exponentially. In other words, as we move to the left on the chart (towards past values), the weighting that they receive in the computation of the MA decreases rapidly (faster than it would be in a linear progression), and the most recent prices are far more significant, as a result, in determining the value of the indicator.</p><br />

<h2 align="left">Smoothed Moving Averaged</h2>
<p>The smoothed moving average is similar to EMA, except that it takes all available data into account. The earliest price values are never discarded, but receive a lower weighting, and possess a smaller role in determining the value of the indicator. As its name hints, the smoothed moving average is mostly used to smoothen the price action, removing short-term volatility, allowing us a better understanding of the long term momentum of the market.</p><br />
<h2 align="left">Linear Regressed Moving Average</h2>
<p>This moving average is similar to the MA, except that the weighting factors are linear, not exponential. For example, the price of the earliest period (n) is multiplied with 1, the following, more recent period (n-1) is multiplied by a factor of, 2, and the next one is multiplied by 3, and so on, until we reach the present timeframe. In this context, the most recent prices receive greater emphasis, and the latest fluctuations, rises or falls are depicted with greater clarity, aiding trade decisions.</p><br />

<h2 align="left">Using the Moving Averages</h2>
<p>Although there are almost countless improvised, and professionally created strategies based on moving averages, there are three typical methods that lie at the basis of most of the strategies and methods.</p><br />
<h2 align="left">Crossovers</h2>
<p>Crossovers arise when the price rises or falls below the moving average, signaling the end or the beginning of a new trend. Crossovers are some of the most common occurrences in technical trading, and as such, do not grant us a great deal of predictive power in the evaluation of the market action. They are used best in combination with other tools and techniques when we seek to evaluate the price action with greater confidence.</p><br />
<h2 align="left">Moving Average Trends</h2>
<p>Apart from trends in the price action itself, the moving average can also have its own trend at times. It is possible to take advantage of these trends for determining entry/exit points. Although not as reliable as the price trend itself when used alone, it can be an efficient way to confirm the price action when used in combination with it.</p><br />
<h2 align="left">Divergence/Convergence</h2>
<p>A divergence occurs when the trend is in ascendance, but the moving average is descending. A convergence happens when the market trend is bearish, but the moving average contradicts it by registering higher highs. These events are thought to signal a future reversal. When the price action is contradicted by the indicator values, the expectation is that the market is about to run out of energy, and it may be a good time to open a counter-trend position. It is important to remember that timing is very uncertain in all these formations, and that the anticipated reversal may never occur. Especially in strong trends, it is common to observe divergence/convergence phenomenon arise regularly without leading to any significant reversal. Still, it is the rarest, and most popular technical configuration preferred in the interpretation of a moving average.</p><br />
<h2 align="left">MA Hopping</h2>
<p>We use this term to define a method of trading in which MAs of different periods are used as successive resistance levels for the price action to breach. For example, we expect an ongoing trend to first breach the 1-hour, then the 3-hour, then the 10, and 40-hour moving averages in succession, and may choose to open a position at each of these successive indicators. Since we anticipate continuity between levels indicated by these MAs, we will maintain our positions as the price hops, so to speak, between them.</p>
<p>We'll examine each of these methods as we discuss each moving average type in its own article. To learn more about how these calculations are performed you are invited to visit the relevant page.</p><br />
<h2 align="left">Conclusions</h2>
<p>The main weakness of the moving average is its lagged nature. In many cases, and especially for short term fluctuations, by the time a moving average captures a market event, it may have already ended. The moving average will only note a developing market pattern after it has been set up convincingly, and if the pattern is short-lived, it will not be possible to trade it, and we may suffer from whipsaws as well.</p>
<p>The strength of this indicator type is its ease-of-use, clarity, and simplicity. They can be easily incorporated into any overall strategy, and it is also possible to devise methods exclusively through the usage of the moving average as well. The great versatility of this indicator type makes it a valuable addition to any trader's arsenal of technical tools, regardless of trading style, or the preferred market type.</p><br />
<h1 align="center">Parabolic SAR Indicator</h1>
<p>Parabolic SAR (Stop and Reverse) is an indicator developed by J. Willes Wilder to discover and exploit profitable trends in all kinds of markets. It is a popular tool among technical traders, and a straightforward and as a simple mechanism for analyzing the markets, it offers some unique advantages over other tools.</p>
<p>Below we have a chart of the EURUSD pair depicting the Parabolic SAR in action. We observe that the indicator was able to capture many small reversals with remarkable accuracy. And in those cases where it failed, we see that the thrust of the market action was strong enough to place it into a correct configuration, thereby minimizing the potential losses of a faulty trade.</p><br />
<h2 align="left">Calculation of the Parabolic SAR</h2>
<p>Parabolic SAR is calculated by a recursive formula which ties the prices of one period to another through simple arithmetics.</p>
<p>SAR of Today = SAR of Yesterday + a (EP- SAR of Yesterday)
Or
SAR of Tomorrow = SAR of Today + a(EP-SAR of Today)</p>
<p>EP is the maximum recorded during the time period in consideration. If during each period of analysis a new record is broken, the EP will be updated accordingly, and the SAR value will change.</p>
<p>"a" represents the acceleration factor. It is set at 0.02 in the beginning, and reset each time a new EP is achieved. This is to ensure that the indicator's value will come closer to the EP value every time a new record is broken, but the maximum value for the EP is usually set at 0.2 in order to prevent it from becoming too large and distorting the analytical picture. Due to the higher volatility of the forex market, traders prefer to give an initial value of 0.01 to the acceleration factor on the basis that frequent fluctuations, leaps and bounces in the price action do not justify attaching a lot of significance to arbitrary price highs.</p>
<p>Once the SAR value is calculated one of two courses will be taken in order to derive the signal from the indicator. If tomorrow's SAR remains within today's or yesterday's price range, the indicator is set at the lowest price during that time period. For example, if the SAR is slightly above yesterday's opening lowest price, or close to, but below, yesterday's high, the indicator will be set at today's lowest price.</p>
<p>If on the other hand, tomorrow's SAR value is within tomorrow's price range, the indicator will switch sides. If it is below the price action, it will move to the upside, and if it was on the upside it will come below, signifying a trend switch.</p><br />
<h2 align="left">Trading with Parabolic SAR</h2>
<p>Parabolic SAR is generally regarded as a trend indicator, since other types of markets tend to generate false signals leading to whipsaws and fake breakouts. The best way of trading the Parabolic SAR is to first gauge the direction of the market by using simple tools like trend lines, moving averages, or tools like the average true range, before using Parabolic SAR to trade the shorter-term fluctuations that can be exploited within a longer term framework.
When it is drawn on a chart, the Parabolic SAR will indicate a bullish market if it remains below the price, or supports it, and when it is above the same it is regarded to be suppressing the prices, indicating bearish conditions. Not only is it possible to regard this phenomenon as a signal for the opening of a position, but it also makes sense to use the Parabolic SAR as a stop or take profit level in each trade. For instance, when the price action is bearish, and we have a sell order, one can choose to exit the position when the price action approaches the SAR level by a predetermined number of pips. When the market action is bullish on the other hand, we can use the Parabolic SAR as a support level, and when the price gets too close to it, we can liquidate the trade. It is also possible to use a time-stop while trading with this indicator. In this case, there is no necessity of a market reversal. Instead we determine a timeframe during which the trade will be kept active, but when that period is out, we'll liquidate it even if the Parabolic SAR indicator is indicating positive conditions. This course of action is justified on the basis that in a strongly trending market where this indicator is most useful, lack of progress can be a sign of approaching reversal.</p><br />
<h2 align="left">Conclusion</h2>
<p>This indicator is most useful in a trending market. It is best to use it in combination with other indicators that establish the general direction of the trend at a higher level, while trading short-term volatility with the SAR. The advantages of this technical tool are its simplicity, clarity of signals, ease of interpretation, and tendency to generate concrete points of action during a trending market. These same strengths are also the weaknesses of the indicator. It is sometimes the case that the solid signals of the SAR indicator lack any practical basis. To avoid such conditions, we suggest that you use the SAR indicator with oscillators that signal emerging divergence/convergence scenarios, so that the common problem of whipsaws are reduced in frequency. Ultimately, of course, our best guide should always be money management and prudence in trading, beyond any single technical indicator.</p><br />

<h1 align="center">Oscillators Explained</h1>
<p>Oscillators are a group of indicators that confine the theoretically infinite range of the price action into more practical limits. They were developed due to the difficulty of identifying a high or low value in the course of trading. Although we may have mental concepts of what is high or low in a typical day's price action, the volatile and chaotic nature of trading means that any high can easily be superseded by another one that sometimes follows on the heels of a previous record, and negates it swiftly. In short, practice and experience tell us that prices in themselves are very poor guides on what constitutes an extreme value in the market, and. oscillators aim to solve this problem by identifying indicator levels that hint at tops or bottoms, and helping us in the decision process.</p><br />
<h2 align="left">Why should use I oscillators?</h2>
<p>There are two ways of using an oscillator. One is to determine turning points, tops and bottoms, and this style is usually useful while trading ranges only. Oscillators are also used trending markets, but in this case our only purpose is joining the trend. Highs or lows, tops or bottoms are used for entering a trade in the direction of the main trend.</p><br />
<h2 align="left">Types of Oscillators</h2>
<p>There are many kinds of oscillators available for the trader's choice, and although they have different names and purposes in accordance with the creators' vision, there are a small number of distinctions that determine which group an oscillator falls into, and where or how it can be used, as a result.</p>
<p>It is possible to group oscillators first on the basis of their price sensitivity. Some, like the Williams Oscillator, are very sensitive to the price action. They reflect market movements accurately, but under the default configuration do not refine movements into simpler, clearer signals for the use of the trader. Oscillators like the RSI are less volatile, and are more precise in their signals, but also less sensitive to the price action, which means that two different movements of different volatility and violence may still be registered in the same range by the RSI, while the Williams Oscillator analyzes it more accurately to reflect its violent nature. Some oscillators provide limit values to determine various oversold/overbought levels, while others create their signals through the divergence/convergence phenomenon alone. In general, oscillators that provide oversold/overbought levels are useful in range patterns, others are mostly used in trend analysis. Let's take a look at a few examples to have an idea of the different types oscillators used by traders.</p>
<p>
1.	MACD:: The MACD is one of the most commonplace indicators. It is a trend indicator, and it is useless in ranging markets. MACD has no upper or lower limits, but does have a centerline and some traders use crossovers to generate trade signals.
2.	RSI: RSI is another commonplace and relatively aged indicator used by range traders. It is almost useless in trending markets.
3.	Williams Oscillator: An excellent tool for analyzing trending markets, especially those highly volatile, the Williams Oscillator requires some commitment and patience to get used to, but it is popular, partly due to its association with the trading legend Larry Williams.
4.	Commodity Channel Index: The CCI is particularly useful for the analysis of commodities and currencies that move in cycles. It is not as popular as the others mentioned above, but it has been around for some time, and has stood to test of time. The indicators are examined in greater detail in their own article.</p><br />
<h2 align="left">Using the Oscillators</h2>
<p>Each oscillator has its own how-to of trading the markets. Some provide the aforementioned overbought/oversold levels for trade decisions, others are used by traders through various technical phenomena to generate the desired signals. But it is generally agreed that the best way of using this indicator type is the divergence/convergence method. Although this method is also prone to emitting false signals at times, it does not occur as frequently as the other technical events such as crossovers or the breach of overbought/oversold levels, and is therefore preferred over other styles of analysis.</p><br />
<h2 align="left">Conclusions</h2>
<p>Oscillators can be used in ranging and trending markets, and since, depending on the timeframe, even a range pattern can be broken down to smaller trends, it can also be possible to use trend oscillators in range trading as well. Creativity and experience are the main requirements for the successful use of these versatile technical tools. If you seek to use them in your own trading, it is a good idea to do a lot of backtesting, and demo trading just to get used to the parameters, and to gain an idea of what works and what does not. In time, your own trading style will develop which will determine the indicator types that you enjoy most and find most versatile and useful for you. You can begin by studying the various articles on oscillators at this website.</p><br />

<h1 align="center">Larry Williams Indicators</h1>
<p>As the name suggests, Larry Williams indicators are a group of technical tools developed and published by the renowned commodity and stock trader Larry Williams in a series of books and articles since the 80s.  In this article we'll present a brief overview of the most popular ones among the tools developed by him. The indicators themselves will be examined in their own articles at this website.</p><br />
<h2 align="left">Larry Williams: A Trading Legend</h2>
<p>Born in 1942 in Montana, Larry Williams is one of the most famous traders of our time. His greatest claim to fame arises out of his success in the World Cup Championship of Futures Trading in 1987. During this contest, Larry Williams was able to turn $10000 to $1,1 million in about twelve months using techniques that he had developed earlier in his carrier. Since then, he has been the author of articles and books about trading, providing the public with interesting insight to his trading skills, and sharing the technical basis of his success with other traders. In 1997, his daughter Michelle Williams also gained the first place in the same competition.</p><br />
<h2 align="left">Types of Williams Indicators</h2>
<p>Larry Williams created a large number of indicators the rationale behind which is explained in his various books and articles. With his celebrity status in the trading community, it was not long before brokers incorporated his ideas into their own software and trading packages, and today the Williams Percent Range indicator, for example, is a part of the standard technical charting toolbox of just about any broker.</p><br />
<h2 align="left">Williams Percent Range Indicator</h2>
<p>Similar to the Stochastics indicator, Williams Percent Range Indicator is one of the most popular tools created by the famous trader. It is basically a volatile oscillator the signals of which are acted upon only if they last for a considerable period of time. Unlike the RSI, for example, one doesn't buy or sell at overbought/oversold levels, but awaits the consolidation of the price in these regions before any conclusion is reached.</p>
<p>The Williams Oscillator is widely available as part of most forex charting packages.</p><br />
<h2 align="left">Williams A/D (Accumulation, Distribution) Indicator</h2>
<p>Larry Williams has developed many ways of measuring the accumulation/distribution phenomenon in the markets in light of volatility, open interest, volume, and many other factors. These indicators are not as common as the percent range indicator, but they are popular and highly regarded by traders.</p><br />
<h2 align="left">Williams Ultimate Oscillator</h2>
<p>The Ultimate oscillator was created for the purpose of reducing the effect of short-term large movements on the signals generated. The indicator measures accumulation/distribution in the market, instead of focusing on the price directly, and can also be configured to fluctuate in accordance with three different time cycles corresponding to 7, 14, and 28-period measurements.</p>
<p>The indicator is used on the basis of divergence/convergences, and a signal is confirmed with a trend break,  which is a gap in the price indicating that the momentum of the price action has changed decisively. Positions are opened on the basis of highs or lows registered on the oscillator.</p><br />
<h2 align="left">Greatest Swing Value Indicator</h2>
<p>This is not so much as an indicator as it is a concept introduced by Larry Williams in one of his books. Used with simple bar charts, or in more complicated configurations, the Greatest Swing Value concept is used by swing and range traders for establishing trade patterns.</p><br />
<h2 align="left">Blast Off Indicator</h2>
<p>This indicator is not very common, since it is a proprietary tool, but Larry Williams will not hesitate to talk about it during his appearances in meetings or seminaries with other traders.</p><br />
<h2 align="left">Conclusion</h2>
<p>Needless to say, Williams indicators are very popular in the trading community. The trading record of the creator of these tools is enough in itself, for many people, to justify their use. Nonetheless, anyone who regards these tools as charmed items that will protect their users from error is likely to be disappointed in short order. As with any indicator, using the Williams indicators requires, above all, a reasonable degree of skepticism about their effectiveness. No indicator will eliminate the necessity of a diligent and focused approach to risk management. These tools are no exception.</p>
<p>In this group, the most popular ones are the Williams Percent Range indicator and the Ultimate Oscillator. Although we're going to examine both of them in greater detail in a separate article, we may note here that as  trend indicators that are volatile themselves, and will generate good results only if the signals emitted by them are used with great conservatism. In other words, pick the most convincing, and long-lasting signals, as you'll have plenty of them to act upon in any case. It is possible to do very well with these great indicators when one treats risk sensibly and does not get carried away by his successes, or allow his failures to chop off a large chunk of his account by trading too much.</p><br />

<h1 align="center">Momentum Indicators</h1>
<p>What is momentum? The term has a specific meaning in physics, and perhaps it is easier to understand the momentum of prices by considering an analogy. We know that the speed of a swinging pendulum will vary along the vertical axis, for example, as the pendulum moves from the bottom to the uppermost extent of its oscillation. Although the vertical movement of the pendulum is zero at the top of its range (since otherwise it would fly away), the forces acting on it at the same point is maximum. Conversely, as the pendulum reaches its maximum speed, the forces generating the speed are at their minimum. The oscillation of force and speed that creates the observed back and forth movement in the pendulum is very similar to the oscillation of prices in the market.</p>
<p>As the prices move between successive extremes, the speed of the price action reaches its maximum at a point where the entry of new traders or money has peaked. Thereafter, the trend will continue to generate new highs in all likelihood unless the continuous nature of the price action is broken by an unexpected event, but since the amount of new buyers or sellers steadily decreases, achieving and sustaining new highs will be harder. And just as the case with the pendulum, as the driving force of the trend dries out (timeframe or size of the trend is irrelevant), opponents of the trend will sooner or later achieve dominance, and will drive the price action in the opposite direction, replicating tick-tock pattern that is familiar to most traders.</p>
<p>Momentum indicators aim to characterize and portray these swings of the price. Needless to say, there are no precise, deterministic rules in trading and technical analysis that can give such satisfactory results as those obtained by the physicist, but the momentum indicators do help us place the price action into the context of trader enthusiasm which then enables the determination of the underlying trend's strength.</p><br />
<h2 align="left">How to use Momentum Indicators</h2>
<p>There is of course no rock-solid rule about the use of this type of indicator. A capable trader can create profitable trades even with a most unlikely combination of indicators. On the other hand, there are some common rules that would help many newcomers by restricting them to a less volatile, less emotional course of action. This section is mostly aimed at supplying such a set of rules.</p>
<p>Momentum indicators are not directional indicators. They are most beneficial in the context of an existing trend already identified by a trader who is unsure about when to join the same. In other words, we know our destination, and we know the vehicle that we'll board, but we would like to board it at such a time and under such conditions that the risk of an accident or crash is minimal. Momentum indicators facilitate this task by telling us when the trend has enough fuel to burn, so to speak, in volume, trader enthusiasm, and overall market dynamism. For instance, when using the stochastics indicator, a trader may choose to exploit a crossover as a sign that the trend has achieved enough momentum to justify a new trade. In a range pattern, the RSI may be used to determine reversals which are equivalent to the highs or lows of the pendulum.</p>
<p>Another, and perhaps more popular way of using momentum indicators is making use of them in light of the divergence/convergence phenomenon. In this case, the trader does not seek to confirm the price action with a favorable momentum signal, and aims, instead, to identify the price levels where momentum is contradicting the price action. We had discussed that the net force acting on a pendulum will be zero when it reaches its greatest speed at its highest or lowest level. Similarly, the trader seeks out phases of the market action where momentum is falling rapidly, while the price action accelerates towards a point of reversal. When that point is reached, we enter a counter-trend position with the aim of benefiting from the ensuing correction.</p><br />
<h2 align="left">Types of Momentum Indicators</h2>
<p>Momentum indicators are both popular and numerous. By definition, they are also oscillators, and all the general principles that apply to oscillators discussed in the relevant articles apply to momentum indicators as well. Here we'll mention a few examples briefly, in order to preserve the completeness of our presentation.</p>
<p><b>-Oscillators:</b> Oscillators such as the RSI, MACD, CCI or Stochastics indicators are momentum indicators as well. They swing back and forth between predetermined levels, and can be traded on the basis of the divergence/convergence phenomenon, as well as the simpler crossover techniques.</p><br />
<p><b>-Momentum Indicator:</b> As its name indicates, this indicator is dedicated to measuring the impulse of the trend. It is perhaps the most basic type of momentum indicator.</p>
<p><b>-Rate of Change:</b> An advanced version of the momentum indicator, the rate of change indicator presents an easier-to-interpret, more refined picture of the market's emotional configuration, and is useful in any market that displays a strong tendency to oscillate.
The Williams Oscillator is also a momentum indicator.</p>
<p>Many guides and textbooks on technical analysis tend to restrict momentum indicators to range trading, but it is perfectly possible to use them in trends provided that one solidifies their signals through confirmation from another class of indicators that is more suitable to a trending market.</p>
<p>We'll also discuss each of these indicators in their separate articles in greater detail.
Conclusion</p>
<p>Momentum indicators should be used with other types of indicators that establish directionality. Combining them with Fibonacci indicators, which generate far more precise trading points for exploitation, is also a reliable technique. Although there are a large number of indicators that measure momentum, it is probably not a good idea to use more than one of them on a single trade. And especially in strongly directional markets, such as those where developing bubbles are dominant, it is not a great idea to depend too much on momentum readings, even when strong divergence/convergence patterns exist.</p><br />


<h2 align="left">Stochastics Indicator</h2>
<p>The stochastics indicator is one of the oldest analytical tools in the market today. It was introduced in the 50s by George C. Lane, and has been popular ever since with both novice and experienced traders. It's great advantage is its simplicity. It's very easy to plot and evaluate it, and while it's just as prone to generating false signals as any other indicator, the vast amount of analysis and study available means that its behavior is better understood by traders and analysts.</p><br />
 <h2 align="left">Calculation of the Stochastics Indicator</h2>
<p>The stochastics indicator is composed of two parts. The %K component is an oscialltor itself, and it is usually provided separately as the Williams Oscillator in most trading software packages. Let's first see how it is calculated, although we'll discuss it separately under its own heading.</p>
<p>%K = 100 x ( Recent Close - Lowest Low )/( Highest High- Lowest Low)
Here the highest high, the lowest low, indicate the values created during the entire timeframe on which the indicator is being applied.</p>
<p>The %K component tells us where the most recent range falls with respect to the maximum registered in the timeframe of our analysis. For example, if the most recent range is 50 pips, while the largest range is 100, the value of the component would be 100 x (50/100) = 50, which would mean that the latest range is in the 50 percentile of the maximum value in the analysis period.</p>
<p>The %D component is the 3-period MA of  %K. Both are plotted on the chart to help us derive signals. The MA can be a simple, or an exponential moving average depending on the desired degree of sensitivity to the latest market action.</p>
<p>The two types of slow and fast stochastics indicators both depend on the same principles, with the difference between them being that the slow stochastics indicator applies a longer period moving average to the %K component in order to smooth out crossovers and indicator volatility. The slow stochastics indicator is usually more reliable, although it emits a smaller number of trade signals.</p><br />
<h2 align="left">Trading with Stochastics Indicator</h2>
<p>The stochastics indicator is for the most part a range pattern indicator. It is used to determine overbought/oversold levels in a manner similar to the RSI. The oversold level is at 20, while the overbought level resides at 80. Although this is the most basic way of using this indicator, it is in fact rarely used because of the tendency to create false signals. Instead, as with most other oscilators, convergence/divergence patterns are sought between the price and the indicator, and then trading decisions are made sometimes supported by secondary concepts like the price extremes, or crossovers that can sometimes signal momentum changes.
Both for the fast and slow stochastics indicators, indicator crossovers are used to create trade signals on the basis of the movement of the %K component. The %K component is the faster moving of the two components, and when it rises above, or falls below the slower %D, a buy or sell signal will be generated.</p><br />
<h2 align="left">Accessibility</h2>
<p>Stochastics oscillator is available with just about any trading software in the market, since it is a part of the most basic technical analysis toolbox. All the major platforms provided by MGForex, Easy-Forex, ForexYard make this indicator available.</p><br />
<h2 align="left">Conclusion</h2>
<p>What is the best way of using the stochastics indicator? In a ranging marker, with a relatively calm trading environment, traders can use simple crossovers or overbought/oversold levels in formulating their trading strategies. In more complicated market conditions, it is probably the best choice to seek the divergence/convergence phenomenon, and to confirm with volatility indicators, or moving averages to pick only the most reliable configurations. You can, for example, choose a less volatile, ranging market as determined by the Bollinger Bands, or the ATR, for trading with the Stochastics indicator in trendless market conditions.
It is not a good idea to use the stochastics indicator in strongly trading markets, especially if you depend on overbought/oversold levels for trade decisions. Trending markets can be brutal in the way they breach these limits, and it simply is not worth the risk to try to test them with range indicators .</p><br />
<h1 align="center">Ichomoku Kinko Hyo Indicator</h1><br />
<h2 align="left">Overview</h2>
<p>The Ichimoku Kinko Hyo, Ichimoku Cloud, Equilibrium Chart was developed by Japanese newspaper writer Goichi Hosoda in 1968, and it is more familiar to futures and equity traders than to forex traders. In spite of its lacklustre popularity, however, the indicator is powerful, and innovative, worthy of greater attention than it receives currently in the trader community.To understand how this indicator functions, we need to recall that the ichimoku cloud is a strategy more than an indicator. It combines two support/resistance levels to create a cloud, or reversal zone, and depends on the crossover of the tenkan and kijun sen to generate trade alerts. But since it is a strategy, it is not as versatile as some of the other, more basic tools like moving averages or the RSI. Thus it performs better in a more specific market type in which it is more effective as a strategy.</p>
<p>A typical trading scenario is generated when the red and blue lines generate a crossover, as observed on first and second vertical bars on the chart above. The purple and reddish dotted, areas, termed the cloud, or kumo, function as support/resistance levels where a possible reversal is indicated.</p>
<p>Let's a take deeper look at how the indicator is calculated.</p><br />
<h2 align="left">Calculation</h2>
<p>The Ichimoku Kinko Hyo indicator is calculated from four components with the following formulae:</p>
<p>1. Tenkan Sen: (Highest High + Lowest Low)/2 over 7-8 bars
2. Kijun Sen: (Highest High + Lowest Low)/2 over the past 22 bars
3. Senkou Span A: (Tenkou Sen + Kijun Sen)/2 plotted over 26 bars into the future
4. Senkou Span B: (Highest high + Lowest Low)/2 over the past 44 bars, plotted 22 bars ahead
Tenkan sen and kijun sen are essentially moving averages, and are used in a similar way with tenkan sen being the more sensitive of the two. The senkou span A and B are the main features of the ichimoku indicator separating it from an ordinary oscillator. These two values come together to create a cloud, or kumo, which is used a support or resistance level by traders depending on market conditions.</p><br />
<h2 align="left">Usage of Ichimoku Kinkyo</h2>
<p>In spite of the apparent of complexity, the Ichimoku cloud is very simple and easy to use once you get a grasp of how it works, and what it is. As we mentioned at the beginning, the indicator is more of a strategy than an indicator. It combines four separate tools into a single visual framework for trade decisions.</p>
<p>Trade signals are generated as the tenkan sen moves below or above the slower moving kijun sen, in a way very similar to the interaction of moving averages in the MACD, or the stochastics indicators. A bearish trend is indicated by the tenkan sen moving below the kijun sen, and vice versa. Once such a signal is generated, and we anticipate the development of a trend and open a position, the kumo (cloud) of the indicator comes into the picture. As mentioned elsewhere, the cloud is the support/resistance zone of the trade. In a bearish position, we expect that the price action will remain outside of the kumo most of the time, and if it remains in that region for too long, it may be time to reconsider or close the trade. Conversely, we will maintain our position for as long as the support/resistance zone established by the cloud holds. This makes 'letting profits run' a much easier task than it is with a simple crossover/ support/resistance strategy, since the problems created by volatility are handled better by the ichimoku cloud.</p>
<p>Take profit orders can be placed at any point outside of the cloud. Stop-loss orders should be placed in or at the edge of the cloud, and money management methods must always take into account the possibility of maximum losses being incurred as the cloud support fails.</p><br />
<h2 align="left">Conclusion</h2>
<p>There are a couple of conclusions that we can draw from our discussion of the indicator.
The Ichimoku cloud indicator is a complex tool that provides a lot of information when it is depicted on the chart. Two moving averages, and a layered support/resistance area makes the implementation of complex strategies a possibility, but also renders the addition of any extra moving averages, vertical Fibonacci levels, or arbitrary support/resistance data superfluous. Understanding the components of the indicator, and the rationale behind its usage will be helpful in avoiding noise on our charts. If we possess credible information about where order clusters are, it is not a good idea to utilize the ichimoku kinko hyo</p>.
<p>The kumo, or cloud component of the indicator is useful in conditions of high market volatility where strict adherence to single support/resistance levels on the chart may result in lots of false signals and small failed trades. By providing a zone, instead of a line, this indicator can be helpful in isolating more reliable signals from noise. We could easily construct a support/resistance zone with multiple Fibonacci indicators, or simple support/resistance lines, and decrease the number of generated signals by refusing to act on mere breaches of the outer and inner lines. The strength of the Ichimoku cloud against such a strategy is automation and speed. You have to depend on the same basic formulae in all market conditions, with little manual intervention,but at the same acquire greater flexibility in your decisions.</p>
<p>In conclusion, we can summarise the advantages of the Ichimoku cloud as concision, automation, and simplicity. Its disadvantages are a lack of customizability, and blanket coverage for lots of possible market configurations. If you think that the particular market situation is suitable for trading with two support/resistance lines, and two moving averages, the indicator is a perfect choice. If you conclude that other or more tools are necessary, it is a good idea not to take much time with the Ichimoku cloud.</p><br />


</p>
</div>
</div>