<div class="client_content">
<div class="whttrading"><br /><br />
<h1 align="center">Fundamental Analysis and Technical Analysis</h1><br /><br />
<h2 align="left">What is fundamental analysis?</h2>
<p>Fundamental analysis in Forex is a type of market analysis which involves studying of the economic situation of countries to trade currencies more effectively. It gives information on how the big political and economical events influence currency market. Figures and statements given in speeches by important politicians and economists are known among the traders as economical announcements that have great impact on currency market moves. In particular, announcements related to United States economy and politics are the primary to keep an eye on.Analysis of the market is not merely a part of trading; it is the essence of forex trading. Market analysis generally takes one of two approaches, or a merging of the two approaches. The first approach, fundamental analysis, considers factors and events, opinions and policies that might impact the future value of a currency. The second approach, called Technical Analysis, involves the study of historic and current currency values and trading volume. Whatever the approach, the objective of analysis-technical, fundamental, or blended-is to attempt to project currency price direction and identify trading opportunities.The  analysis for forex traders focuses on factors that might influence currency values, including interest rates, the overall state of affected economies, central bank and government monetary and fiscal policies, Gross National Product, etc. Some of the factors that should be considered in fundamental analysis are described below:</p><br />

<h2 align="left">The Economy</h2>
<p>While the worldwide recession of 2008 was a factor for all countries, it affected different countries to different extents, and different nations responded to the challenge using varying strategies. Those differences resulted in changes in the relative value of world currencies. In addition to global events and responses, more localized changes in localized economic conditions affect the value of individual currencies. Events that have a detrimental effect on economies tend to decrease the relative values of economies, while those events that have a positive effect tend to increase the value of related currencies. For example, a sustained drought in Australia might result in downward pressure on the Australian Dollar, while an increase in oil prices can result in a jump in the Canadian Dollar.</p><br />
<h2 align="left">Political (In) Stability</h2>
<p>All major currencies are issued by politically stable countries. However political stability changes over time-sometimes abruptly. Dramatic changes in political stability can affect currency values dramatically by affecting confidence in the currency, and by reducing economic activity. Fundamental analysis of currency trading should include keeping close watch on changes in political stability in related regions, starting with base knowledge of regional political stability. A good source of basic political information on countries is the Central Intelligence Agency of the United States. Their website has a World Factbook and is a good place to start a general analysis of the baseline politics and stability of a country.</p><br />

<h2 align="left">Government Policy</h2>
<p>Government policies - particularly monetary and fiscal policy can have substantial impact on the value of the nation's currency. Nations often use interest rate as an important tool in monetary policy - increasing interest rates to cool economic growth and curb inflation, and decreasing rates to stimulate economies. Fiscal policy also impacts currency values; higher taxation can slow economic growth, while low taxation and spending can stimulate economies. Of course, these factors will affect currency values.</p><br />

<h2 align="left">Observing Other Participants</h2>
<p>Another fundamental aspect of forex trading is the understanding other market participants and the effect they may have on currency values. Governments and Central Banks, private banks and other financial institutions, hedge funds and other speculators may all play a role. Central banks or hedge funds can buy the currency, and raise the price in one day. Large private banks can also affect the market with their activity, but usually only over a long term period. The actions of private speculators can also impact currency prices.</p><br />

<h2 align="left">Events and Reports</h2>
<p>Agencies of many world governments track statistical data that reveals aspects of the economy. Often, the agency will release the results of their data collection and analysis at regular scheduled intervals. Such reports often relate directly to regional economic conditions, like inflation rates, gross national product, employment rates, trade balance and inflation. Those reports can have a dramatic impact on currency values. The forex trader should be aware of the timing of such reports, and adjust trading strategy appropriately - sometimes simply exiting all related trades (being flat) because of the uncertainty that precedes such reports. Fortunately, the timing of such events is known in advance, and reported widely on online economic calendars.</p>
<p>Other events can also impact currency values dramatically. Such events include meetings of central bank committees or release of national budgets.</p><br />

<h2 align="left">Economic Theories and Models</h2>
<p>Forex trading is a recent development, but stocks and equities have been studied for a long time, and economic theories and models abound on the best way to analyze information.
These models look at various aspects, such as the activities of business in the economy, and even the most basic psychological attributes such as belief that the country is moving in the right direction. Business activity is a long term indicator of strength in the economy. A widespread belief that a country's fundamental economic indicators are accurate will sustain a currency's value, even if the short term economic outlook may be bleak.</p>
<p>The theories available to the investor include those on currency parity and national balance of payments, and models on interest rates, the role of money, and the types of assets purchased in a country. The data used by these instruments include economic and employment statistics, interest and inflation rates, and sales information such as gross domestic product, trade and capital flows and retail sales. By using this information, the trader can evaluate the fundamentals of a nation's economy, and ensure the basic research is sound.</p><br />
<h2 align="left">Technical Analysis and Charting</h2>
<p>Often, forex markets are studied through the use of charts that show market prices over a period of time. Traditionally, financial charts were drawn by hand. Fortunately, today such charts are available through forex trading platforms, and are available online on websites.</p><br /> <h2 align="left">Such as this one:</h2>  
<p>Charts are used extensively by traders, to study past patterns of price movement, identify ongoing trends, and to try forecasting future price movement. Technical indicators are often used in conjunction with charts. Simple technical indicators include moving averages. Many complex indicators are available, which involve complex mathematical analysis of price data. Fortunately, online charts do all the calculations automatically, and display the results as overlays on the chart.</p>
<p>Forex charts are usually presented in one of several formats, including line, bar chart and candlestick.</p><br />
<h2 align="left">Bar Charts</h2>
<p>Perhaps the most popular type of forex chart is known as the bar chart. Bar charts plot price (in the vertical dimension) over a period of time (in the horizontal dimension). Each bar on the chart represents a fixed time period, which can often be selected by the viewer if the chart is being viewed online or through a forex trading platform. Each single bar (or 'tick') on a bar chart illustrates 4 distinct prices for the period of time represented by the chart. Those prices are: open - currency price at the start of the period; high - the highest price during the period; low - the lowest price during the period; and close - the price of the currency at the end of the period.</p>
<p>With experience at reading charts, a trader can visualize market action quickly from a bar chart or can study the chart in depth to identify trends, levels of price support and resistance, indications of potential trend reversal, repeating cycles, and much more. The same capabilities exist in another popular form of chart, which displays the same information, but in a different format.</p><br />
<h2 align="left">Candlestick Charts</h2>
<p>Like bar charts, candlestick charts plot forex price levels over time. Candlesticks display the same information as bar charts for each "tick": open, high, low and close. However, the presentation of those four prices is dramatically different than in a bar chart.
In a candlestick chart, each individual time period (or tick) is shown as a small graphical image called a candlestick. High and low prices for the period are shown as thin vertical lines at the top and bottom, extending beyond the thicker "main body" of each candlestick. The top and bottom of the main body of each candlestick represent the opening and closing prices for the period, and the color of the candlestick main body signifies which was higher: the closing price or the opening price. Often, a higher close is signified by a white, hollow, green or lightly colored main body, and a lower close is indicated by a solid black or reddish main body.</p>
<p>Traders trained and experienced in the use of candlestick charts look for visual patterns, and specific candlestick formations that signal potential trend changes or other market activity.</p><br />
<h2 align="left">Technical Analysis</h2>
<p>Technical Analysis goes hand-in-hand with forex charting. Technical analysis attempts to forecast future price movement through the mathematical analysis of past price action. For many traders, technical analysis is the most important tool for examining the market. Technical analysis involves the study of past and forex prices-often though the use of charts-with the objective of predicting future prices movements and trends, and identifying opportunities for profitable forex trading.</p>
<p>Many traders advocate technical analysis as the most (or only!) reasonable method to attempt to predict prices. That opinion is based on the idea (and cliche) that the "market action discounts everything". That statement means that all factors that can be known that can impact currency prices are already reflected in the currency price. (Of course, few technical traders would dare ignore pending events, such as the release of economic reports discussed in the section above.</p>
<p>In addition to the belief that the "market action discounts everything, fundamental analysis is based on two additional ideas: Prices move in trends: this truism is apparent by observing a forex chart. Currency prices tend to move in the same direction for periods of time.</p><br />

<h2 align="left">Market history repeats itself:</h2> 
<p>Again, some examples of repetitive cycles can be observed on almost any forex chart. However, this premise proposes an idea more subtle: that for a set of general setup conditions in currency price history, currency prices are likely to respond in direction and manner similar to their response to the same initial conditions in the past.</p>
<p>Various simple tools can be used in technical analysis, such as moving averages, trend lines and support levels, or the advanced trader might choose from a wide range of advanced analyses and theories including relative strength index, Fibonacci studies, cycles, and many more.</p>
<p>Some popular fundamental analyses include Elliott Wave Theory, Fibonacci Studies, and Pivot Points.The Elliott Wave Theory holds that markets are affected by the psychology of the population, and move in response to this psychology in a predictable pattern. The theory was developed in the 1920's for stock markets and is now being used in forex trading.</p>
<p>Fibonacci Studies look at the relationship of numbers and apply the same sequence analysis to the forex market, to project the direction the market will move.</p>
<p>Pivot Points refers to the point at which the currency changes direction and increases or decreases over the day. Information from the previous day is examined to see where the pivot point will be for the current trading day.</p>
<p>All of these tools provide the trader with the perspective needed to ensure trades are accurate and profit is maximized.</p>
<p>Many books have been written about fundamental analysis, and there is much more to learn on the topic.</p><br />



<h2 align="left">Technical Analysis vs. Fundamental Analysis</h2>
<p>Technicals are based on forecasting the future using past price movements, also known as price action. Fundamentals, on the other hand, incorporate economic and political news to determine the future value of the currency pair.</p> 

<p>The question of which is better is far more difficult to answer. We have often seen fundamental factors rapidly shift the technical outlook, or technical factors explain a price move that fundamentals cannot. So the answer to the question is to use both. Both methods are important and have a hand in impacting price action. The real key, however, is to understand the benefit of each style and to know when to use each discipline. Fundamentals are good at dictating the broad themes in the market, while technicals are useful for identifying specific entry and exit levels. Fundamentals do not change in the blink of an eye: in the currency markets, fundamental themes can last for weeks, months and even years.</p> <br />

<h2 align="left">Using Both to Make a Move</h2>
<p>For example, one of the biggest stories of 2005 was the U.S. Federal Reserve's aggressive interest rate tightening cycle. In the middle of 2004, the Federal Reserve began increasing interest rates by quarter-point increments. The Fed let the market know very early on that it was going to be engaging in a long period of tightening and, as promised, it increased interest rates by 200 basis points in 2005. This policy created an extremely dollar-bullish environment in the market that lasted for the entire year.</p> 

<p>Against the Japanese yen, whose central bank held rates steady at zero throughout 2005, the dollar appreciated 19% from its lowest to highest levels. USD/JPY was in a very strong uptrend throughout the year, but even so, there were plenty of retraces along the way. These pullbacks were perfect opportunities for traders to combine technicals with fundamentals to enter the trade at an opportune moment.</p> 
<p>Fundamentally, it was clear that the market was a very dollar-positive environment; therefore, technically, we looked for opportunities to buy on dips rather than sell on rallies. A perfect example was the rally from 101.70 to 113.70. The retracement paused right at the 38.2% Fibonacci support, which would have been a great entry point and a clear example of a trade that was based on fundamentals but looked for entry and exit points based on technicals.</p>  
<p>In the USD/JPY trade, trying to pick tops or bottoms during that time would have been difficult. However, with the bull trend so dominant, the far easier and smarter trade was to look for technical opportunities to go with the fundamental theme and trade with the market trend rather than to trying to fade it.</p><br />

</p>
</div>
</div>