<div class="client_content">
<div class="whttrading"><br /><br />
<h1 align="center">Terms and Conditions</h1>
<p>The use of this Site, including the material included and services granted by it, constitutes your agreement to these terms, and you are therefore requested to read them carefully. A certain number of the services are subject to your explicit approval and to the terms and conditions specified below, and without your explicit approval you will not be able to use such services.</p><br />
<h2 align="left">Risk Disclosure:</h2> <p>Trading financial instruments with high investment leverage constitutes speculative trading with a particularly high level of risk. Trading or speculative investment of currencies or any other financial asset implies a high degree of risk of sustaining capital loss. Due to the fact that forex trading could amount to significant financial loss, it is hereby advised to execute such investments using capital that is not intended for current living expenses or of critical importance to the trader.As trading foreign exchange on margin carries a high level of risk, It may not be suitable for all investors. The high degree of leverage can work against you as well as for you. Before deciding to invest in foreign exchange you should carefully consider your investment objectives, level of experience, and risk appetite. Past performance is not indicative of future results, as returns may vary according to market conditions. Trading in foreign exchange is speculative and may involve the loss of entire principal; therefore, funds placed and used under forex signal services should be risk capital funds that if lost will not significantly affect oneâ€™s personal financial well being. No representation is being made that participating in forex signal services/subscriptions or managed forex trading program will necessarily lead to profit. Investors may incur into a series of consecutive losses and substantial equity-draw-downs that can deplete their funds before the occurrence of any meaningful profit. Hypothetical or simulated performance results have certain limitations. Unlike an actual performance record, simulated results do not represent actual trading. Also, since the trades have not been executed, the results may have under-or-over compensated for the impact, if any, of certain market factors, such as lack of liquidity. Simulated trading programs in general are also subject to the fact that they are designed with the benefit of hindsight. No representation is being made that any account will or is likely to achieve profit or losses similar to those shown.</p><br />
<h2 align="left">Subscription Policy:</h2><p> After your successful subscription with all the functionality, you will be regarded our resistered member. As a membe, you will get all the facities provided by the company. We do not renew any package automatically after the subscription period is over. In case of renew our package or take it again, you have to renew it manually or you may subscribe as new member again.</p>

<h2 align="left">Personal Data Safety:</h2><p> The information and email address you provide during resistering in our service will not be shared with any other organization. It will be used only by globalforexsignal to send you news and information about our company and our products. You may also unsubscribe from news and information service if you wish to. The personal data that we collect from you is safely stored via physical, electronic means and procedural controls, in accordance with applicable legislation and it is treated CONFIDENTIAL, at all times.</p><br />

<h2 align="left">Refund Policy:</h2> <p>Globalforexsignal professional team is always careful in making the clients happy and satisfied in their trade. However, clients are suggested to understand our signal before going on trade as we usually do not support any dispute. If you do not want to  use our service or get frustated let us know, Understanding your condition our team decides whether you really deserve any refund or not.On the basis of the recommendation of the team we may refund your payment if possible. Therefore our clients are always suggested carefully consider their  investment objectives, level of experience, and risk appetite.</p><br />

<h2 align="left">Information Copyright:</h2>  <p>This website is the owner of each every detail and information that you able find on the various pages of this website. Every content are held under the copyrights law and you cannot copy, reproduce, publish on you blog, website, forum or forward to anyone who is not the member of this site. If you are found to circulate or distribute the information of the site in any form, via print or digital media, you are liable to face legal action for infringement of the copyright law.</p>
</p><br />
</div>
</div>