<div class="client_content">
<div class="whttrading"><br />
<h1 align="center">Why Loss in Forex Trading</h1>
<p>
Traders may lose easily if they are not strategic. Globalforexsignal’s expert team is working 24 hours in analyzing the market trends and provide the customers reliable signals. You need not to worry if you just follow our signals. For the general knowledge of the clients we are just discussing the following matters.</p><br />
<h2 align="left">Absence of a sound trading plan:</h2>
<p>Next to having unreasonable expectations with regards to the risks associated with forex trading and the amount of time required to be successful, a common mistake made by new traders is the lack of a trading plan. In reality, there are two aspects to this plan, an overall objective for your trading activities and a plan for each trade you make.</p>
<p>Your overall objective should include the currencies that you intend to deal in, the amount of leverage you will use, and the amount of time you intend to devote to your trading activities. Your plan must also include a realistic rate of return you expect to achieve. In addition to your overall objectives plan, you also need an exit strategy plan for each trade you make that includes the upper and lower boundaries of the trade.</p>
<p>In other words, you must identify the level at which you will close positions and take your profits (take profit order) or in the case of a losing trade, the level at which you are prepared to go before you get out of the trade thus limiting your losses (limit order). We will talk more about stop loss and take profit instructions later.</p> <br />

<h2 align="left">Unreasonable expectations:</h2>
<p>First off, stop believing all the "get rich quick" hype still perpetrated by some forex dealers. Yes, there are those that do get rich trading forex but some people also get rich selling houses. In either case, it does not happen overnight and it might take years to gain the experience and insight to turn forex trading into a full time, successful occupation.
As a new trader, if you manage to stay in the game without losing all your money in the first few months as is all too common - then you may be able to learn what is required to be profitable. In other words, don't quit your day job just yet.</p> <br />
<h2 align="left">Lack of experience:</h2>
<p>Forex trading - like any new initiative - has a learning curve. However, unlike learning a new skill such as learning to play guitar for instance, you are not risking your entire savings while discovering the difference between a major and minor chord. Learning about the currency markets and basic trading principles solely on a trial and error basis is not a recommended approach for gaining the skills necessary to be a successful forex trader.
Most online forex brokers offer a practice version of their trading platform that offers the very same experience as a live trading application. Typically, once you create a practice account, you are free to trade and deal as you wish risking only the "play" money used to seed your account.</p>
<p>With a practice account, you can see how the market reacts to economic forces including news events without actually risking your investment capital. However, you must treat this account seriously if you expect to learn from the experience. If you simply shrug off a loss without understanding why the loss occurred, then you are wasting your time and setting yourself up for disappointment. Take advantage of this unique forex market training tool before committing your money to a real trading account.</p> <br />
<h2 align="left">Lack of discipline:</h2>
<p>A plan is only of value if you actually have the patience and the discipline to follow it. While this can be difficult, it is necessary if you expect to be successful, and it is this very reason why developing a plan prior to the trade is so fundamental. As rates fluctuate, you can easily get caught up in the market and it is only human nature that you will begin to second guess your actions. If, for instance, the rate moves up surpassing your original take profit point, you may be tempted to hold out for an even higher return, alternatively, if the price drops below your limit level but you believe there is a big rebound just around the corner, you may be tempted to keep the order open on the hopes of a reversal.</p>
<p>But does either scenario really make sense? If before you entered the trade you had a sound reason for establishing both your take profit and your loss limit levels, how likely is it that conditions have changed so much that now you are prepared to throw your previous assessments out the window in the heat of the battle? Can you be sure that you are not acting on emotion rather than sound analysis?</p>
<p>This is why a plan is so important - it allows you to avoid the emotion that is bound to arise during times of volatility.</p>
<p>Now this is not to say that a trading plan can never be revised - in fact, your overall objectives should be re examined every few months or even more frequently if required. As well, it may be necessary sometimes to abandon a plan mid trade if market conditions warrant but this should be the exception and not the norm.</p>
<p>And yes, sometimes the market can be so volatile that no amount of planning will produce positive results. In this case, maybe the best option is simply not to trade until you can get a better handle on things. Never allow yourself to fall into the "I have to do something" trap - sometimes the best plan is to do nothing.</p> <br />
<h2 align="left">Failure to include stop loss and take profit instructions:</h2>
<p>When you place a market order and leave it open - that is, enter a trade at the market price without instructions to close the order - you are in effect, gambling with the total value of your account. For this reason, you should consider adding stop loss instructions to all open positions.</p>
<p>For instance, if you are holding a long GBP/USD position, you can include a stop loss instruction that automatically sells your long position if the rate falls to a certain level. In this way, you can limit the amount that you could lose on any given trade - even if you are unable to constantly monitor your account.</p>
<p>Take profit orders are similar in that they allow you to establish the rate at which you want open positions closed in order to lock in profits. Again, you simply need to identify the rate at which to take the profits, and the trading system closes the position without further intervention on your part.</p> <br />
<h2 align="left">Excessive leverage:</h2>
<p>Depending on your experience level, trade leverage can be a powerful tool to help you maximize returns, or it can be the cause of your downfall. It is not something to be taken lightly and if you do not understand how it works, don't trade until you do understand.</p> <br />
<h2 align="left">Holding too many open trades:</h2>
<p>Fighter pilots call it "helmet fire" and it happens when too much is happening around you too quickly for you to react. In the cockpit of a jet fighter, it can get you killed - as a forex trader, you may not end up dead but you will probably end up broke.</p> <br />
<h2 align="left">Holding losing positions too long:</h2>
<p>One of the things that really separates seasoned forex traders from those just starting out is their ability to determine when a losing trade is not going to reverse the trend. Rather than "hold and hope", disciplined traders will take the loss and get out much more quickly.
This is another reason to set protective stops on all your trades, if you include effective stops when you submit a new trade, you can at least limit your losses without having to spend too much time "babysitting" the order. If the trade hits the stop, you will lose the amount committed but you also protect the bulk of your capital, leaving you with funds to move into something else that, hopefully, will be more profitable.</p>
<p>Sometimes, you just have to treat these things as life lessons - learn and move on.</p><br />
<h2 align="left">Thinking about the "big win" more than effective cash management, also known as greed:</h2>
<p>This one is pretty straight forward - greed, or more correctly, how greed can cause you to enter into ridiculous trades. This must be the same gene that causes some people to keep "doubling down" even when the odds are so against them that it make no sense at all. If you want to gamble, go to Vegas.</p> <br /> 
<h2 align="left">Ignoring rate spread fluctuations and the impact spreads have on profitability:</h2>

<p>Exchange rate spreads - the difference between the bid and the ask price - are of utmost importance and directly affect the profitability of each trade. You need to be aware that spread differentials can fluctuate wildly during the day - sometimes to the point of turning a profitable trade into a loosing one.</p>
<p>You also need to understand that spreads will widen during off market hours when volumes and liquidity are lower. In addition, spreads tend to widen ahead of important news such as an impending interest rate decision or the latest employment results.</p> 
<p>Global Forex Singal analyising every details provide signal so that the traders may trade without thinking much about it and get comfortable profit.</p>

</p><br />
</div>
</div>