<div class="client_content">
<div class="whttrading"><br />
<h1 align="center">Why Forex Trading</h1>
<p>Trading in the foreign exchange market can be dynamic, exciting and lucrative. While investors have many options in the global investment and speculation marketplace, forex offers advantages over other types of speculative financial vehicles.</p><br />
<h2 align="left">Compared with Futures and Stocks:</h2>
<p>In some ways forex trading is much like stock trading. Buying stocks and other equities for the long term is an investment. Buying the same products to profit from short term price movement is speculation. Most often, traders trade foreign currency in the forex market for speculative reasons that can be compared to the short term purchase of stocks or other equities. Most often, the goal of forex traders is to buy currencies, hold them for a short period, and then sell them with the intent of profiting by favorable changes in price.</p>
<p>Despite these similarities to futures and equities trading, the forex market differs from futures and equities markets in advantageous ways:</p><br />
<h2 align="left">24 hour market:</h2>
<p>Whereas futures, and especially stocks and other equities are usually only traded during business hours, forex is traded in a 24 hour market. Investors can participate in the market at any time, 24 hours per day, excluding only a short period on weekends. If you have Internet access forex Brokers connect can connect traders to their trading platform, to allow access from anywhere at almost any time.</p><br />
<h2 align="left">Ease of Short-Selling:</h2>
<p>A trade is considered to be "long" when it involves the purchase of an asset. A trade is considered to be "short" when it is a sale of property not yet owned, or perhaps purchased on margin.</p>

<p>Therefore, short selling refers to the practice of selling an asset that you do not yet own. Short sellers benefit when the price of the asset decreases. Short selling in huge volumes can help to drive down the price of a stock to fall to the profit of the short sellers. For that reason, short selling in stock markets is restricted to help prevent manipulation of stock prices and unfair opportunities for some investors.</p><br />
<h2 align="left">Not so in forex markets:</h2>
<p>In fact, even the concept of "short selling" has less meaning for forex trades. In the forex market, every trade necessarily includes a purchase of one currency and a sale of another-essentially a long-buy and a short-sell simultaneously. Whether the market is rising or falling is merely one factor or a matter of perspective in trading currencies.
For example, if a trader expects the U.S. Dollar to fall relative to the Canadian Dollar, he would sell USD (U.S. Dollars) and buy CAD (Canadian Dollars). The transaction generates both a long position in Canadian Dollars, and a short position in US Dollars - a net neutral position, until the relative price of the currencies changes.
For that reason, short-selling is not an issue, and is not regulated in the forex market.</p><br />
<h2 align="left">Immediate Order Execution and Price Certainty:</h2>
<p>Stock or futures transactions can take time to occur. From the moment that an order is placed, a transaction in futures or equities can take minutes or even hours to complete, depending on the technologies employed and the volume of trading in the marketplace. Those delays can be challenging to the nerves and to the back account, since in the time that the order takes to execute (or "fill"), the equities or futures price might have changed substantially-a factor usually called slippage.
In contrast, online forex transactions are usually immediate; they are effective as soon as the trade order is submitted by the click of a computer mouse. Because of that immediacy, the trade price is known at the time of the order. There is no surprising slippage, and seldom any of the uncertainty that accompanies stocks or futures orders.</p><br />
<h2 align="left">Manipulation Is More Difficult; Analysis Is Easier:</h2>
<p>Sometimes markets are susceptible to manipulation, especially if they are fairly small or if there few trades taking place. Those same conditions can make a market difficult to analyze, because prices can be volatile and subject to change in response to relatively small pressures.</p><br />
<h2 align="left">The forex market is different:</h2>
<p>The forex market is the largest financial market in the world. According to the 2007 Triennial Survey done for the BIS (Bank for International Settlements), average daily trading in the forex market is $3.2 trillion. By comparison, the global equity market in 2006 was approximately $280 billion, or 10 times smaller than the forex market. This market is huge, not only in terms of dollars, but also in terms of geography.</p>
<p>Forex trading occurs around the globe in countless locations, and not in centralized exchanges such as are used for futures and equities trading. While large financial and commercial institutions might dominate other markets, the size and decentralized nature of the forex market makes it more difficult to manipulate. Even the Central Banks of large nations usually do not have the capital to influence forex markets directly (although it is important to understand that Central Banks can influence currency rates through other means, such as through monetary policy and interest rates).</p>
<p>This large size also means that forex is almost a pure market, in an economic theory sense, with each party entering the market on equal terms. This makes meaningful analysis of the market more likely, as economic models and technical analyses are more easily applied to this orderly market.</p><br />
<h2 align="left">Influence by Analysts Less Likely:</h2>
<p>In equities and stocks, industry and market pundits sometimes develop a large following of speculators. Those followers can represent a substantial amount of capital-enough to cause movements in smaller or less liquid markets. The huge size of the forex market-particularly in commonly-traded currencies-makes it resistant to pressures exerted by the followers of individual market analysts.</p>
<p>The forex markets also provide a more subtle balance that helps curb influence and overt manipulation. This balance is provided through the responsiveness of the forex marketplace.</p>
<p>When parties to a transaction have equal knowledge, both are more likely to be satisfied with the result. In the forex market, participants come closer to equal knowledge than in other markets because the market reacts quickly to events as they occur. The advantage of this characteristic is that any analysis that is flawed will not have an effect over a long period of time. Any flaw will soon be revealed by the market action itself.</p><br />

<h2 align="left">The Forex Market Is Less Complex Than Equities Market:</h2>
<p>Currencies in the forex market are relatively simple to follow, with only 10 major currencies and less than 100 minor currencies. By contrast, futures and stock markets are much more complicated, with tens of thousands of stocks and hundreds of futures. Plus, the complex market landscape is continuously changing, as more corporations form or disappear in the stock market, or as new commodities are added or removed from the futures market.</p><br />
<h2 align="left">Price Certainty and Liquidity:</h2>
<p>The forex market is the largest in the world with $3.2 trillion changing hands each day. It is also very volatile, as traders can react to situations in real time and the market moves in response to those reactions. Yet the Internet basis and resulting quick trade execution of forex markets provides for both liquidity and price certainty. A trader can enter or exit the market at any time in most currencies, making it a liquid market. Since trades are made in real time, the price locked when the trade is made, resulting in none of the slippage experienced in equities or futures markets, and therefore providing price certainty.</p><br />
<h2 align="left">No Commissions:</h2>
<p>Another advantage of forex trading over stocks and futures is the commission structure. Most forex brokers do not charge a commission on a trade. Their fee is a share of the "spread" of each trade, which is the difference between the buying and selling price, (the bid and ask prices).</p><br />
<h2 align="left">Limited Loss compared to Other Margin Accounts:</h2>
<p>The online structure of forex trading has a further advantage not found in the futures and stock markets. Futures, forex and (sometimes) equities are traded "on margin"-meaning that the trader has usually borrowed funds to purchase the asset. In all three types of margin accounts, the trader generally needs to keep funds on deposit in a special margin account. When the traders account suffers a loss, funds in the margin account are used to cover the loss. In futures and equities margin trading, the losses can exceed the funds deposited in the margin account; when that happens, the trader is liable for the loss, and must repay the brokerage for the losses in excess of funds deposited in their margin account.This usually cannot happen with forex trading.
Forex positions are usually automatically exited (or offset) by the broker's trading platform before the traders account goes into deficit. This means that any loss is usually limited to the size of the margin account.</p>
<p>To restate this important point, for clarity: in other markets, halts in trading, poor liquidity, or a delay between margin account deficit and the closing of an open position can result in a substantial drop below the margin funds available in the trader's account. In such cases, the trader is liable for all losses in equities or futures margin trading-even beyond the amount in the traders' margin account. In contrast, forex traders are not exposed to risks beyond the value of their margin account.
Despite these advantages, forex trading does share some pitfalls with other types of speculation.</p><br />
</div>
</div>